
#please do not edit this file if you dont know what youre doing

















# This file is executed on every boot (including wake-boot from deepsleep)
#import esp
#esp.osdebug(None)
import webrepl
webrepl.start()


import network
import time
import machine
wifi = network.WLAN(network.AP_IF)
wifi.active(True)  # Activate the AP mode
wifi.config(essid='webrepl', password='731235')  # Set the SSID and password for the AP
wifi.active(True)
print(wifi.ifconfig())  # Get the IP address of the AP
print("waiting for ota devices [timeout in 5 secs]")

try:
    import machine
    import ssd1306
    import time
    from oled import Write, GFX, SSD1306_I2C
    from machine import Pin, PWM, I2C
    from machine import Pin, PWM, I2C
    from ssd1306 import SSD1306_I2C
    import ubuntu_12

    # Define the I2C pins and display resolution
    i2c = machine.I2C(scl=machine.Pin(22), sda=machine.Pin(21))
    oled = ssd1306.SSD1306_I2C(128, 64, i2c)
    write12 = Write(oled, ubuntu_12)

    # Clear the display
    oled.fill(0)
    oled.show()

    # Display text on the OLED
    ipstr = str(wifi.ifconfig())
    write12.text("-- [webrepl mode] timeout in 5secs -----", 20, 25)
    oled.show()
except:
    print("oled/display failed continuing to boot")






time.sleep(5)
if wifi.status('stations') == 0:
    print("no devices found [continuing to boot :) ]")
    wifi.active(False)
print("Booting >>>>>>>>>")
